<?xml version="1.0"?>
<robot name="mybot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="PI" value="3.1415926535897931"/>

    <xacro:property name="chassisHeight" value="0.1"/>
    <xacro:property name="chassisLength" value="0.4"/>
    <xacro:property name="chassisWidth" value="0.2"/>
    <xacro:property name="chassisMass" value="50"/>

    <xacro:property name="casterRadius" value="0.05"/>
    <xacro:property name="casterMass" value="5"/>

    <xacro:property name="wheelWidth" value="0.05"/>
    <xacro:property name="wheelRadius" value="0.1"/>
    <xacro:property name="wheelPos" value="0.2"/>
    <xacro:property name="wheelMass" value="5"/>

    <xacro:property name="laserScanerSize" value="0.05"/>
    <xacro:property name="laserScanerMass" value="0.1"/>

    <xacro:property name="slingshot_cylinder_lenght" value="0.8"/> 
    <xacro:property name="slingshot_cylinder_radius" value="0.02"/>
    <xacro:property name="slingshot_platform_l" value="0.2"/>
    <xacro:property name="slingshot_platform_w" value="0.2"/>
    <xacro:property name="slingshot_platform_h" value="0.01"/>
 
    <xacro:property name="slingshot_platform_border_l" value="0.2"/>
    <xacro:property name="slingshot_platform_border_w" value="0.02"/>
    <xacro:property name="slingshot_platform_border_h" value="0.1"/>

    <xacro:include filename="$(find mybot_description)/urdf/mybot.gazebo" />
    <xacro:include filename="$(find mybot_description)/urdf/materials.xacro" />
    <xacro:include filename="$(find mybot_description)/urdf/macros.xacro" />

    <link name="$(arg param_prefix)_tf/footprint" />

    <joint name="$(arg param_prefix)_tf/base_joint" type="fixed">
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/> 
      <parent link="$(arg param_prefix)_tf/footprint"/>
      <child link="$(arg param_prefix)_tf/chassis"/>
    </joint>

    <link name='$(arg param_prefix)_tf/chassis'>
      <collision> 
        <geometry> 
          <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
        </geometry> 
      </collision>
      <visual> 
        <geometry> 
          <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
        </geometry> 
        <material name="orange"/>
      </visual>
      <inertial> 
        <mass value="${chassisMass}"/> 
        <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
      </inertial>
    </link>

    <joint name="fixed" type="fixed">
      <origin xyz="${casterRadius-chassisLength/2} 0 ${-chassisHeight/2}" rpy="0 0 0"/>
      <parent link="$(arg param_prefix)_tf/chassis"/>
      <child link="$(arg param_prefix)_tf/caster_wheel"/>
    </joint>

    <link name="$(arg param_prefix)_tf/caster_wheel">
      <collision>
        <geometry>
          <sphere radius="${casterRadius}"/>
        </geometry>
      </collision>
      
      <visual>
        <geometry>
          <sphere radius="${casterRadius}"/>
        </geometry>
        <material name="red"/>
      </visual>

      <inertial>
        <mass value="${casterMass}"/>
        <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
      </inertial>
    </link>

    <wheel lr="left" tY="-1"/>
    <wheel lr="right" tY="1"/>

    <joint name="base_joint2" type="fixed">
      <axis xyz="0 1 0" rpy="0 0 1.57" />
      <origin xyz="${chassisLength/2 - 1.1 * laserScanerSize/2} 0 ${chassisHeight/2 + laserScanerSize/2}" rpy="0 0 0"/>
      <parent link="$(arg param_prefix)_tf/chassis"/>
      <child link="$(arg param_prefix)_tf/laserScaner"/>
    </joint>

    <link name="$(arg param_prefix)_tf/laserScaner">
      <collision>
        <geometry>
          <box size="${laserScanerSize} ${laserScanerSize} ${laserScanerSize}"/>
        </geometry>
      </collision>

      <visual>
        <geometry>
          <box size="${laserScanerSize} ${laserScanerSize} ${laserScanerSize}"/>
        </geometry>
        <material name="blue"/>
      </visual>

      <inertial>
        <mass value="${laserScanerMass}" />
        <box_inertia m="${laserScanerMass}" x="${laserScanerSize}" y="${laserScanerSize}" z="${laserScanerSize}" />
      </inertial>
    </link> 
</robot>
